CREATE TEMP TABLE IF NOT EXISTS seed_menu_content(template_slug TEXT,section_slug TEXT,item_name TEXT,included INTEGER,optional INTEGER,configurable INTEGER,group_slug TEXT,sort_order INTEGER,notes TEXT);
DELETE FROM seed_menu_content;
INSERT INTO seed_menu_content VALUES
('buffet-especial','entradas','Barquinhas com antepastos',1,0,0,NULL,10,''),('buffet-especial','entradas','Mini torradas com antepastos',1,0,0,NULL,20,''),
('buffet-especial','buffet-principal','Costelinha ao molho barbecue',1,0,0,NULL,10,''),('buffet-especial','buffet-principal','Estrogonofe de frango',0,1,0,'escolha-de-frango',20,''),('buffet-especial','buffet-principal','Medalhão de frango',0,1,0,'escolha-de-frango',30,''),
('buffet-especial','acompanhamentos','Arroz branco',1,0,0,NULL,10,''),('buffet-especial','acompanhamentos','Batata palha',1,0,0,NULL,20,''),('buffet-especial','acompanhamentos','Batata rústica',1,0,0,NULL,30,''),('buffet-especial','acompanhamentos','Mix de saladas',1,0,0,NULL,40,''),
('buffet-crepe-frances','entradas','Mini torradas com antepasto de frango',1,0,0,NULL,10,''),('buffet-crepe-frances','entradas','Mini salgados fritos',1,0,0,NULL,20,''),
('buffet-crepe-frances','crepes-salgados','Calabresa',0,1,1,'sabores-de-crepes-salgados',10,''),('buffet-crepe-frances','crepes-salgados','Queijo e catupiry',0,1,1,'sabores-de-crepes-salgados',20,''),('buffet-crepe-frances','crepes-salgados','Frango, queijo e catupiry',0,1,1,'sabores-de-crepes-salgados',30,''),('buffet-crepe-frances','crepes-salgados','Palmito e azeitona',0,1,1,'sabores-de-crepes-salgados',40,''),('buffet-crepe-frances','crepes-salgados','Camarão com catupiry',0,1,1,'sabores-de-crepes-salgados',50,''),('buffet-crepe-frances','crepes-salgados','Tomate, queijo e manjericão',0,1,1,'sabores-de-crepes-salgados',60,''),('buffet-crepe-frances','crepes-salgados','Quatro queijos',0,1,1,'sabores-de-crepes-salgados',70,''),('buffet-crepe-frances','crepes-salgados','Queijo e presunto',0,1,1,'sabores-de-crepes-salgados',80,''),('buffet-crepe-frances','crepes-salgados','Rúcula com queijo e tomate',0,1,1,'sabores-de-crepes-salgados',90,''),
('buffet-crepe-frances','crepes-doces','Banana, açúcar e canela',0,1,1,'sabores-de-crepes-doces',10,''),('buffet-crepe-frances','crepes-doces','Morango com chocolate',0,1,1,'sabores-de-crepes-doces',20,''),('buffet-crepe-frances','crepes-doces','Prestígio',0,1,1,'sabores-de-crepes-doces',30,''),('buffet-crepe-frances','crepes-doces','Doce de leite',0,1,1,'sabores-de-crepes-doces',40,''),('buffet-crepe-frances','crepes-doces','Romeu e Julieta',0,1,1,'sabores-de-crepes-doces',50,''),('buffet-crepe-frances','crepes-doces','Chocolate',0,1,1,'sabores-de-crepes-doces',60,''),
('buffet-crepe-frances','molhos','Molho ao sugo',1,0,0,NULL,10,''),('buffet-crepe-frances','molhos','Tomate com ervas',1,0,0,NULL,20,''),('buffet-crepe-frances','molhos','Molho quatro queijos',1,0,0,NULL,30,''),('buffet-crepe-frances','molhos','Queijo ralado',1,0,0,NULL,40,''),
('buffet-crepe-frances','salada','Alface americana',1,0,0,NULL,10,''),('buffet-crepe-frances','salada','Rúcula',1,0,0,NULL,20,''),('buffet-crepe-frances','salada','Tomate-cereja',1,0,0,NULL,30,''),('buffet-crepe-frances','salada','Manga',1,0,0,NULL,40,''),('buffet-crepe-frances','salada','Queijo parmesão',1,0,0,NULL,50,''),
('buffet-crepe-frances','temperos-e-molhos','Tempero convencional',1,0,0,NULL,10,''),('buffet-crepe-frances','temperos-e-molhos','Azeite',1,0,0,NULL,20,''),('buffet-crepe-frances','temperos-e-molhos','Vinagre',1,0,0,NULL,30,''),('buffet-crepe-frances','temperos-e-molhos','Sal',1,0,0,NULL,40,''),('buffet-crepe-frances','temperos-e-molhos','Limão',1,0,0,NULL,50,''),('buffet-crepe-frances','temperos-e-molhos','Molho tártaro',1,0,0,NULL,60,''),
('buffet-crepe-frances','acompanhamentos','Cobertura de chocolate',1,0,0,NULL,10,'Acompanhamento dos crepes doces'),('buffet-crepe-frances','acompanhamentos','Cobertura de morango',1,0,0,NULL,20,'Acompanhamento dos crepes doces'),('buffet-crepe-frances','acompanhamentos','Farofa de castanhas',1,0,0,NULL,30,'Acompanhamento dos crepes doces'),('buffet-crepe-frances','acompanhamentos','Sorvete de creme',1,0,0,NULL,40,'Acompanhamento dos crepes doces'),
('buffet-feijoada','entradas','Linguiça toscana acebolada',1,0,0,NULL,10,''),('buffet-feijoada','entradas','Mini pastéis de queijo',1,0,0,NULL,20,''),('buffet-feijoada','entradas','Mix de frios',1,0,0,NULL,30,'Queijo, presunto e azeitona'),
('buffet-feijoada','buffet-principal','Carne seca',1,0,0,NULL,10,''),('buffet-feijoada','buffet-principal','Paio',1,0,0,NULL,20,''),('buffet-feijoada','buffet-principal','Linguiça calabresa',1,0,0,NULL,30,''),('buffet-feijoada','buffet-principal','Lombo',1,0,0,NULL,40,''),('buffet-feijoada','buffet-principal','Costelinha',1,0,0,NULL,50,''),
('buffet-feijoada','acompanhamentos','Arroz branco',1,0,0,NULL,10,''),('buffet-feijoada','acompanhamentos','Farofa rica',1,0,0,NULL,20,''),('buffet-feijoada','acompanhamentos','Couve refogada',1,0,0,NULL,30,''),('buffet-feijoada','acompanhamentos','Molho vinagrete',1,0,0,NULL,40,''),('buffet-feijoada','acompanhamentos','Molho de pimenta',1,0,0,NULL,50,''),('buffet-feijoada','acompanhamentos','Costelinha assada',1,0,0,NULL,60,''),('buffet-feijoada','acompanhamentos','Torresmo',1,0,0,NULL,70,''),('buffet-feijoada','acompanhamentos','Mandioca frita',1,0,0,NULL,80,''),('buffet-feijoada','acompanhamentos','Banana à milanesa',1,0,0,NULL,90,''),('buffet-feijoada','acompanhamentos','Laranja',1,0,0,NULL,100,''),('buffet-feijoada','acompanhamentos','Mix de saladas',1,0,0,NULL,110,''),
('buffet-feijoada','sobremesas','Mousse de limão',1,0,0,NULL,10,''),('buffet-feijoada','sobremesas','Salada de frutas',1,0,0,NULL,20,''),
('buffet-boteco','entradas','Mix de amendoins',1,0,0,NULL,10,''),('buffet-boteco','entradas','Mix de mini salgados fritos',1,0,0,NULL,20,''),('buffet-boteco','entradas','Mix de conservas',1,0,0,NULL,30,'Azeitonas, queijo e presunto'),
('buffet-boteco','buffet-principal','Frango a passarinho',1,0,0,NULL,10,''),('buffet-boteco','buffet-principal','Linguiça acebolada',1,0,0,NULL,20,''),('buffet-boteco','buffet-principal','Isca de alcatra',1,0,0,NULL,30,''),('buffet-boteco','buffet-principal','Caldo verde',1,0,0,NULL,40,''),
('buffet-boteco','acompanhamentos','Pão francês',1,0,0,NULL,10,''),('buffet-boteco','acompanhamentos','Arroz branco',1,0,0,NULL,20,''),('buffet-boteco','acompanhamentos','Batata frita',1,0,0,NULL,30,''),('buffet-boteco','acompanhamentos','Mandioca frita',1,0,0,NULL,40,''),('buffet-boteco','acompanhamentos','Mix de saladas',1,0,0,NULL,50,''),('buffet-boteco','sobremesas','Pudim de leite',1,0,0,NULL,10,''),('buffet-boteco','sobremesas','Romeu e Julieta',1,0,0,NULL,20,''),
('buffet-comida-mineira','entradas','Caldinho de feijão',1,0,0,NULL,10,''),('buffet-comida-mineira','entradas','Bolinho de arroz',1,0,0,NULL,20,''),('buffet-comida-mineira','entradas','Bolinho de mandioca',1,0,0,NULL,30,''),
('buffet-comida-mineira','buffet-principal','Frango com quiabo',1,0,0,NULL,10,''),('buffet-comida-mineira','buffet-principal','Vaca atolada',1,0,0,NULL,20,''),('buffet-comida-mineira','buffet-principal','Ragu de calabresa',1,0,0,NULL,30,''),
('buffet-comida-mineira','acompanhamentos','Arroz branco',1,0,0,NULL,10,''),('buffet-comida-mineira','acompanhamentos','Arroz carreteiro',1,0,0,NULL,20,''),('buffet-comida-mineira','acompanhamentos','Feijão tropeiro',1,0,0,NULL,30,''),('buffet-comida-mineira','acompanhamentos','Torresmo pururuca',1,0,0,NULL,40,''),('buffet-comida-mineira','acompanhamentos','Farofa de couve',1,0,0,NULL,50,''),('buffet-comida-mineira','acompanhamentos','Couve refogada',1,0,0,NULL,60,''),('buffet-comida-mineira','acompanhamentos','Banana à milanesa',1,0,0,NULL,70,''),('buffet-comida-mineira','acompanhamentos','Mix de saladas',1,0,0,NULL,80,''),('buffet-comida-mineira','sobremesas','Doce de leite',1,0,0,NULL,10,''),('buffet-comida-mineira','sobremesas','Doce de mamão',1,0,0,NULL,20,''),
('buffet-nordestino','entradas','Dadinho de tapioca',1,0,0,NULL,10,''),('buffet-nordestino','entradas','Escondidinho de carne seca',1,0,0,NULL,20,''),('buffet-nordestino','entradas','Mini pastel de camarão',1,0,0,NULL,30,''),('buffet-nordestino','entradas','Ragu de calabresa',1,0,0,NULL,40,''),
('buffet-nordestino','buffet-principal','Galinhada com quiabo',1,0,0,NULL,10,''),('buffet-nordestino','buffet-principal','Moqueca de peixe',1,0,0,NULL,20,''),('buffet-nordestino','buffet-principal','Cupim assado',1,0,0,NULL,30,''),('buffet-nordestino','buffet-principal','Bobó de camarão',1,0,0,NULL,40,''),
('buffet-nordestino','acompanhamentos','Arroz branco',1,0,0,NULL,10,''),('buffet-nordestino','acompanhamentos','Feijão de corda',1,0,0,NULL,20,''),('buffet-nordestino','acompanhamentos','Baião de dois',1,0,0,NULL,30,''),('buffet-nordestino','acompanhamentos','Farofa rica',1,0,0,NULL,40,''),('buffet-nordestino','acompanhamentos','Mandioca frita',1,0,0,NULL,50,''),('buffet-nordestino','acompanhamentos','Salada vinagrete',1,0,0,NULL,60,''),('buffet-nordestino','acompanhamentos','Mix de saladas',1,0,0,NULL,70,''),('buffet-nordestino','sobremesas','Doce de banana',1,0,0,NULL,10,''),('buffet-nordestino','sobremesas','Romeu e Julieta',1,0,0,NULL,20,''),
('buffet-carnes','entradas','Mini salgados fritos',0,1,0,'escolha-de-entradas',10,''),('buffet-carnes','entradas','Mini salgados assados',0,1,0,'escolha-de-entradas',20,''),('buffet-carnes','entradas','Barquinhas recheadas',0,1,0,'escolha-de-entradas',30,''),('buffet-carnes','entradas','Mini torradas com antepastos',0,1,0,'escolha-de-entradas',40,''),('buffet-carnes','entradas','Mini quiche de presunto e queijo',0,1,0,'escolha-de-entradas',50,''),
('buffet-carnes','buffet-principal','Lagarto ao molho madeira',0,1,0,'escolha-de-carnes',10,''),('buffet-carnes','buffet-principal','Tiras de alcatra',0,1,0,'escolha-de-carnes',20,''),('buffet-carnes','buffet-principal','Medalhão de frango',0,1,0,'escolha-de-carnes',30,''),('buffet-carnes','buffet-principal','Estrogonofe de frango',0,1,0,'escolha-de-carnes',40,''),('buffet-carnes','buffet-principal','Estrogonofe de carne',0,1,0,'escolha-de-carnes',50,''),('buffet-carnes','buffet-principal','Cupim assado',0,1,0,'escolha-de-carnes',60,''),('buffet-carnes','buffet-principal','Costelinha ao molho barbecue',0,1,0,'escolha-de-carnes',70,''),('buffet-carnes','buffet-principal','Fricassê de frango',0,1,0,'escolha-de-carnes',80,''),('buffet-carnes','buffet-principal','Lombo recheado com queijo',0,1,0,'escolha-de-carnes',90,''),
('buffet-carnes','acompanhamentos','Arroz branco',1,0,0,NULL,10,''),('buffet-carnes','acompanhamentos','Batata palha',1,0,0,NULL,20,''),('buffet-carnes','acompanhamentos','Batata sauté',1,0,0,NULL,30,''),('buffet-carnes','acompanhamentos','Salada italiana',1,0,0,NULL,40,''),('buffet-carnes','acompanhamentos','Mix de saladas',1,0,0,NULL,50,''),
('buffet-carnes','sobremesas','Pudim de leite',0,1,0,'escolha-de-sobremesas',10,''),('buffet-carnes','sobremesas','Pavê de chocolate',0,1,0,'escolha-de-sobremesas',20,''),('buffet-carnes','sobremesas','Mousse de maracujá',0,1,0,'escolha-de-sobremesas',30,''),('buffet-carnes','sobremesas','Mousse de limão',0,1,0,'escolha-de-sobremesas',40,''),
('buffet-da-casa','entradas','Mini salgados fritos',1,0,0,NULL,10,''),('buffet-da-casa','entradas','Mini salgados assados',1,0,0,NULL,20,''),('buffet-da-casa','entradas','Barquinhas recheadas',1,0,0,NULL,30,''),('buffet-da-casa','entradas','Mini torradas com antepastos',1,0,0,NULL,40,''),('buffet-da-casa','entradas','Ceviche',1,0,0,NULL,50,''),
('buffet-da-casa','massas','Sorrentino recheado de queijo ao molho branco',1,0,0,NULL,10,''),('buffet-da-casa','massas','Talharim ao molho sugo',1,0,0,NULL,20,''),
('buffet-da-casa','buffet-principal','Medalhão de frango com bacon',1,0,0,NULL,10,''),('buffet-da-casa','buffet-principal','Costelinha ao molho barbecue',1,0,0,NULL,20,''),('buffet-da-casa','buffet-principal','Tiras de alcatra ao molho madeira',1,0,0,NULL,30,''),
('buffet-da-casa','acompanhamentos','Arroz branco',1,0,0,NULL,10,''),('buffet-da-casa','acompanhamentos','Arroz primavera',1,0,0,NULL,20,''),('buffet-da-casa','acompanhamentos','Batata rústica',1,0,0,NULL,30,''),('buffet-da-casa','acompanhamentos','Salada italiana',1,0,0,NULL,40,''),('buffet-da-casa','acompanhamentos','Salada Caesar',1,0,0,NULL,50,''),('buffet-da-casa','acompanhamentos','Mix de saladas',1,0,0,NULL,60,''),
('buffet-da-casa','sobremesas','Pudim de leite',0,1,0,'escolha-de-sobremesas',10,''),('buffet-da-casa','sobremesas','Pavê de chocolate',0,1,0,'escolha-de-sobremesas',20,''),('buffet-da-casa','sobremesas','Mousse de maracujá',0,1,0,'escolha-de-sobremesas',30,''),('buffet-da-casa','sobremesas','Merengue de morango',0,1,0,'escolha-de-sobremesas',40,''),
('buffet-brunch','frios','Queijos frescos',1,0,0,NULL,10,''),('buffet-brunch','frios','Requeijão',1,0,0,NULL,20,''),('buffet-brunch','frios','Frios fatiados',1,0,0,NULL,30,''),('buffet-brunch','frios','Azeitonas verdes',1,0,0,NULL,40,''),('buffet-brunch','frios','Ovos de codorna',1,0,0,NULL,50,''),('buffet-brunch','frios','Salame',1,0,0,NULL,60,''),('buffet-brunch','frios','Antepastos variados',1,0,0,NULL,70,''),('buffet-brunch','frios','Mix de saladas',1,0,0,NULL,80,''),
('buffet-brunch','paes','Mini pão francês',1,0,0,NULL,10,''),('buffet-brunch','paes','Pão de queijo',1,0,0,NULL,20,''),('buffet-brunch','paes','Pão de forma',1,0,0,NULL,30,''),('buffet-brunch','paes','Mini baguetes de queijo',1,0,0,NULL,40,''),('buffet-brunch','paes','Amanteigados de nata',1,0,0,NULL,50,''),('buffet-brunch','paes','Amanteigados de chocolate',1,0,0,NULL,60,''),
('buffet-brunch','salgados','Torta de frango com palmito',1,0,0,NULL,10,''),('buffet-brunch','salgados','Barquinhas assadas',1,0,0,NULL,20,''),('buffet-brunch','salgados','Mini torradas',1,0,0,NULL,30,''),('buffet-brunch','salgados','Ovos mexidos',1,0,0,NULL,40,''),('buffet-brunch','salgados','Mini salgados fritos',1,0,0,NULL,50,''),('buffet-brunch','salgados','Mini salgados assados',1,0,0,NULL,60,''),
('buffet-brunch','bebidas','Café',1,0,0,NULL,10,''),('buffet-brunch','bebidas','Leite',1,0,0,NULL,20,''),('buffet-brunch','bebidas','Iogurte',1,0,0,NULL,30,''),('buffet-brunch','bebidas','Sucos',1,0,0,NULL,40,''),('buffet-brunch','bebidas','Refrigerante',1,0,0,NULL,50,''),('buffet-brunch','bebidas','Água',1,0,0,NULL,60,''),
('buffet-brunch','frutas','Morango',1,0,0,NULL,10,''),('buffet-brunch','frutas','Kiwi',1,0,0,NULL,20,''),('buffet-brunch','frutas','Melancia',1,0,0,NULL,30,''),('buffet-brunch','frutas','Uva',1,0,0,NULL,40,''),('buffet-brunch','frutas','Maçã',1,0,0,NULL,50,''),('buffet-brunch','frutas','Pera',1,0,0,NULL,60,''),
('buffet-brunch','cereais','Granola',1,0,0,NULL,10,''),('buffet-brunch','cereais','Aveia',1,0,0,NULL,20,''),('buffet-brunch','cereais','Manteiga',1,0,0,NULL,30,''),('buffet-brunch','cereais','Mel',1,0,0,NULL,40,''),('buffet-brunch','cereais','Geleias',1,0,0,NULL,50,''),
('buffet-brunch','sobremesas','Salada de frutas',1,0,0,NULL,10,''),('buffet-brunch','sobremesas','Torta de limão',1,0,0,NULL,20,''),('buffet-brunch','sobremesas','Brigadeiros gourmet',1,0,0,NULL,30,''),('buffet-brunch','sobremesas','Mix de doces finos',1,0,0,NULL,40,''),('buffet-brunch','sobremesas','Mini trufas',1,0,0,NULL,50,''),('buffet-brunch','sobremesas','Camafeus',1,0,0,NULL,60,''),
('buffet-finger-foods','entradas','Ceviche',1,0,0,NULL,10,''),('buffet-finger-foods','entradas','Barquinhas recheadas',1,0,0,NULL,20,''),('buffet-finger-foods','entradas','Mini torradas com antepastos',1,0,0,NULL,30,''),('buffet-finger-foods','entradas','Mix de canapés',1,0,0,NULL,40,'Queijo, tomate-cereja e azeitona'),
('buffet-finger-foods','buffet-principal','Escondidinho de carne seca',1,0,0,NULL,10,''),('buffet-finger-foods','buffet-principal','Ragu de calabresa',1,0,0,NULL,20,''),('buffet-finger-foods','buffet-principal','Mini batata recheada',1,0,0,NULL,30,'Bacon, cream cheese e cebolinha'),('buffet-finger-foods','buffet-principal','Ravioli ao molho sugo',1,0,0,NULL,40,''),('buffet-finger-foods','buffet-principal','Nhoque recheado com molho branco',1,0,0,NULL,50,''),
('buffet-finger-foods','fritos','Coxinha',1,0,0,NULL,10,''),('buffet-finger-foods','fritos','Rissole',1,0,0,NULL,20,''),('buffet-finger-foods','fritos','Bolinha de queijo',1,0,0,NULL,30,''),('buffet-finger-foods','fritos','Bolinho de carne',1,0,0,NULL,40,''),('buffet-finger-foods','fritos','Quibe',1,0,0,NULL,50,''),
('buffet-finger-foods','assados','Mini quiche',1,0,0,NULL,10,''),('buffet-finger-foods','assados','Mini esfiha de frango',1,0,0,NULL,20,''),('buffet-finger-foods','assados','Mini esfiha de carne',1,0,0,NULL,30,''),('buffet-finger-foods','assados','Mini esfiha de presunto e queijo',1,0,0,NULL,40,''),('buffet-finger-foods','sobremesas','Merengue de morango',1,0,0,NULL,10,''),('buffet-finger-foods','sobremesas','Pudim de leite',1,0,0,NULL,20,''),
('buffet-de-massas','entradas','Barquinhas recheadas',1,0,0,NULL,10,''),('buffet-de-massas','entradas','Mini torradas com antepastos',1,0,0,NULL,20,''),('buffet-de-massas','entradas','Mini salgados fritos',1,0,0,NULL,30,''),
('buffet-de-massas','massas','Sorrentino de queijo',0,1,1,'escolha-de-massas',10,''),('buffet-de-massas','massas','Ravioli de carne',0,1,1,'escolha-de-massas',20,''),('buffet-de-massas','massas','Capeletti de frango',0,1,1,'escolha-de-massas',30,''),('buffet-de-massas','massas','Talharim com salmão',0,1,1,'escolha-de-massas',40,''),
('buffet-de-massas','molhos','Molho branco',1,0,0,NULL,10,''),('buffet-de-massas','molhos','Molho ao sugo',1,0,0,NULL,20,''),('buffet-de-massas','acompanhamentos','Queijo parmesão',1,0,0,NULL,10,''),('buffet-de-massas','acompanhamentos','Batata sauté',1,0,0,NULL,20,''),('buffet-de-massas','acompanhamentos','Salada italiana',1,0,0,NULL,30,''),('buffet-de-massas','acompanhamentos','Mix de saladas',1,0,0,NULL,40,''),
('buffet-de-massas','sobremesas','Pudim de leite',0,1,0,'escolha-de-sobremesas',10,''),('buffet-de-massas','sobremesas','Pavê de chocolate',0,1,0,'escolha-de-sobremesas',20,''),('buffet-de-massas','sobremesas','Mousse de maracujá',0,1,0,'escolha-de-sobremesas',30,''),('buffet-de-massas','sobremesas','Mousse de limão',0,1,0,'escolha-de-sobremesas',40,''),
('buffet-de-churrasco','entradas','Pão de alho',1,0,0,NULL,10,''),('buffet-de-churrasco','entradas','Queijo coalho',1,0,0,NULL,20,''),('buffet-de-churrasco','entradas','Mix de frios',1,0,0,NULL,30,'Azeitona, presunto e queijo'),
('buffet-de-churrasco','buffet-principal','Alcatra',1,0,0,NULL,10,''),('buffet-de-churrasco','buffet-principal','Contrafilé',1,0,0,NULL,20,''),('buffet-de-churrasco','buffet-principal','Linguiça mista',1,0,0,NULL,30,''),('buffet-de-churrasco','buffet-principal','Asinha de frango',1,0,0,NULL,40,''),('buffet-de-churrasco','buffet-principal','Coxinha de frango',1,0,0,NULL,50,''),
('buffet-de-churrasco','acompanhamentos','Arroz branco',1,0,0,NULL,10,''),('buffet-de-churrasco','acompanhamentos','Arroz à grega',1,0,0,NULL,20,''),('buffet-de-churrasco','acompanhamentos','Farofa especial',1,0,0,NULL,30,''),('buffet-de-churrasco','acompanhamentos','Vinagrete',1,0,0,NULL,40,''),('buffet-de-churrasco','acompanhamentos','Salada de maionese',1,0,0,NULL,50,''),('buffet-de-churrasco','acompanhamentos','Mix de saladas',1,0,0,NULL,60,''),
('buffet-carnes-e-massas','entradas','Barquinhas com antepastos',1,0,0,NULL,10,''),('buffet-carnes-e-massas','entradas','Mini salgados fritos',1,0,0,NULL,20,''),('buffet-carnes-e-massas','entradas','Escondidinho de carne seca',1,0,0,NULL,30,''),
('buffet-carnes-e-massas','buffet-principal','Filet mignon e lagarto ao molho madeira',1,0,0,NULL,10,''),('buffet-carnes-e-massas','buffet-principal','Costelinha assada ao molho barbecue',1,0,0,NULL,20,''),('buffet-carnes-e-massas','buffet-principal','Medalhão de frango ao molho branco',1,0,0,NULL,30,''),('buffet-carnes-e-massas','massas','Sorrentino de queijo',1,0,0,NULL,10,'Acompanha molho ao sugo, molho branco e queijo parmesão'),('buffet-carnes-e-massas','massas','Capeletti de carne',1,0,0,NULL,20,'Acompanha molho ao sugo, molho branco e queijo parmesão'),('buffet-carnes-e-massas','massas','Talharim com salmão',1,0,0,NULL,30,'Acompanha molho ao sugo, molho branco e queijo parmesão'),
('buffet-carnes-e-massas','acompanhamentos','Arroz branco',1,0,0,NULL,10,''),('buffet-carnes-e-massas','acompanhamentos','Arroz primavera',1,0,0,NULL,20,''),('buffet-carnes-e-massas','acompanhamentos','Batata rústica',1,0,0,NULL,30,''),('buffet-carnes-e-massas','acompanhamentos','Salada italiana',1,0,0,NULL,40,''),('buffet-carnes-e-massas','acompanhamentos','Mix de saladas',1,0,0,NULL,50,''),
('buffet-churrasco-fogo-de-chao','entradas','Pão de alho',1,0,0,NULL,10,''),('buffet-churrasco-fogo-de-chao','entradas','Coração de frango',1,0,0,NULL,20,''),('buffet-churrasco-fogo-de-chao','entradas','Tiras de alcatra',1,0,0,NULL,30,''),
('buffet-churrasco-fogo-de-chao','buffet-principal','Costela',1,0,0,NULL,10,''),('buffet-churrasco-fogo-de-chao','buffet-principal','Cupim',1,0,0,NULL,20,''),('buffet-churrasco-fogo-de-chao','buffet-principal','Contrafilé',1,0,0,NULL,30,''),('buffet-churrasco-fogo-de-chao','buffet-principal','Linguiça mista',1,0,0,NULL,40,''),('buffet-churrasco-fogo-de-chao','buffet-principal','Asinha de frango',1,0,0,NULL,50,''),('buffet-churrasco-fogo-de-chao','buffet-principal','Coxinha de frango',1,0,0,NULL,60,''),
('buffet-churrasco-fogo-de-chao','acompanhamentos','Arroz branco',1,0,0,NULL,10,''),('buffet-churrasco-fogo-de-chao','acompanhamentos','Arroz à grega',1,0,0,NULL,20,''),('buffet-churrasco-fogo-de-chao','acompanhamentos','Farofa especial',1,0,0,NULL,30,''),('buffet-churrasco-fogo-de-chao','acompanhamentos','Molho vinagrete',1,0,0,NULL,40,''),('buffet-churrasco-fogo-de-chao','acompanhamentos','Salada de maionese',1,0,0,NULL,50,''),('buffet-churrasco-fogo-de-chao','acompanhamentos','Mix de saladas',1,0,0,NULL,60,'');

-- Sobremesas com escolha de exatamente duas, compartilhadas pelos modelos indicados.
INSERT INTO seed_menu_content
SELECT slug,'sobremesas',item,0,1,0,'escolha-de-sobremesas',ord,'' FROM menu_templates
JOIN (SELECT 'Pudim de leite' item,10 ord UNION ALL SELECT 'Pavê de chocolate',20 UNION ALL SELECT 'Mousse de maracujá',30 UNION ALL SELECT 'Mousse de limão',40)
WHERE slug IN ('buffet-de-churrasco','buffet-carnes-e-massas','buffet-churrasco-fogo-de-chao');

INSERT OR IGNORE INTO menu_categories(name,sort_order,active,created_at,updated_at)
SELECT DISTINCT section.name,100+section.id,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM seed_menu_content data JOIN menu_sections section ON section.slug=data.section_slug;

INSERT OR IGNORE INTO menu_items(category_id,name,slug,source_label,normalized_name,search_aliases,description,calculation_type,calculation_divisor,calculation_multiplier,calculation_weight,active,created_at,updated_at)
SELECT category.id,data.item_name,data.section_slug||'-'||lower(hex(data.item_name)),data.item_name,data.item_name,'',MAX(data.notes),'menu_only',1,1,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP
FROM seed_menu_content data JOIN menu_sections section ON section.slug=data.section_slug JOIN menu_categories category ON category.name=section.name
GROUP BY category.id,data.section_slug,data.item_name;

INSERT OR IGNORE INTO menu_template_sections(menu_template_id,menu_section_id,display_name,sort_order,required,selection_min,selection_max,allow_event_changes,notes,active,created_at,updated_at)
SELECT DISTINCT model.id,section.id,section.name,section.id*10,1,0,NULL,1,'',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP
FROM seed_menu_content data JOIN menu_templates model ON model.slug=data.template_slug JOIN menu_sections section ON section.slug=data.section_slug;

INSERT OR IGNORE INTO menu_template_items(menu_template_section_id,menu_item_id,slug,source_label,normalized_name,description,sort_order,included,optional,configurable,notes,active,created_at,updated_at)
SELECT template_section.id,item.id,lower(hex(data.item_name)),data.item_name,data.item_name,item.description,data.sort_order,data.included,data.optional,data.configurable,data.notes,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP
FROM seed_menu_content data
JOIN menu_templates model ON model.slug=data.template_slug
JOIN menu_sections section ON section.slug=data.section_slug
JOIN menu_template_sections template_section ON template_section.menu_template_id=model.id AND template_section.menu_section_id=section.id
JOIN menu_categories category ON category.name=section.name
JOIN menu_items item ON item.category_id=category.id AND item.name=data.item_name;

CREATE TEMP TABLE IF NOT EXISTS seed_choice_groups(template_slug TEXT,section_slug TEXT,group_slug TEXT,group_name TEXT,min_choices INTEGER,max_choices INTEGER,required INTEGER,allow_extra INTEGER,allow_custom INTEGER,configurable INTEGER);
DELETE FROM seed_choice_groups;
INSERT INTO seed_choice_groups VALUES
('buffet-especial','buffet-principal','escolha-de-frango','Escolha de frango',1,1,1,0,0,0),
('buffet-crepe-frances','crepes-salgados','sabores-de-crepes-salgados','Sabores de crepes salgados',0,NULL,0,1,1,1),
('buffet-crepe-frances','crepes-doces','sabores-de-crepes-doces','Sabores de crepes doces',0,NULL,0,1,1,1),
('buffet-carnes','entradas','escolha-de-entradas','Escolha de entradas',2,2,1,0,0,0),
('buffet-carnes','buffet-principal','escolha-de-carnes','Escolha de carnes',2,2,1,0,0,0),
('buffet-carnes','sobremesas','escolha-de-sobremesas','Escolha de sobremesas',2,2,1,0,0,0),
('buffet-da-casa','sobremesas','escolha-de-sobremesas','Escolha de sobremesas',2,2,1,0,0,0),
('buffet-de-massas','massas','escolha-de-massas','Escolha de massas',0,NULL,0,1,1,1),
('buffet-de-massas','sobremesas','escolha-de-sobremesas','Escolha de sobremesas',2,2,1,0,0,0),
('buffet-de-churrasco','sobremesas','escolha-de-sobremesas','Escolha de sobremesas',2,2,1,0,0,0),
('buffet-carnes-e-massas','sobremesas','escolha-de-sobremesas','Escolha de sobremesas',2,2,1,0,0,0),
('buffet-churrasco-fogo-de-chao','sobremesas','escolha-de-sobremesas','Escolha de sobremesas',2,2,1,0,0,0);

INSERT OR IGNORE INTO menu_choice_groups(menu_template_section_id,slug,choice_group_name,selection_min,selection_max,selection_required,allow_extra_items,allow_custom_item,configurable,sort_order,active,created_at,updated_at)
SELECT template_section.id,data.group_slug,data.group_name,data.min_choices,data.max_choices,data.required,data.allow_extra,data.allow_custom,data.configurable,10,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP
FROM seed_choice_groups data JOIN menu_templates model ON model.slug=data.template_slug JOIN menu_sections section ON section.slug=data.section_slug JOIN menu_template_sections template_section ON template_section.menu_template_id=model.id AND template_section.menu_section_id=section.id;

INSERT OR IGNORE INTO menu_choice_group_items(menu_choice_group_id,menu_template_item_id,sort_order,initially_selected,created_at)
SELECT choice.id,template_item.id,data.sort_order,0,CURRENT_TIMESTAMP
FROM seed_menu_content data JOIN menu_templates model ON model.slug=data.template_slug JOIN menu_sections section ON section.slug=data.section_slug JOIN menu_template_sections template_section ON template_section.menu_template_id=model.id AND template_section.menu_section_id=section.id JOIN menu_template_items template_item ON template_item.menu_template_section_id=template_section.id AND template_item.normalized_name=data.item_name JOIN menu_choice_groups choice ON choice.menu_template_section_id=template_section.id AND choice.slug=data.group_slug
WHERE data.group_slug IS NOT NULL;

-- Blocos compartilhados e sua materialização nos modelos.
CREATE TEMP TABLE IF NOT EXISTS seed_shared_items(block_slug TEXT,section_slug TEXT,item_name TEXT,sort_order INTEGER,configurable INTEGER);
DELETE FROM seed_shared_items;
INSERT INTO seed_shared_items VALUES
('bebidas-padrao','bebidas','Refrigerante - Linha Coca-Cola',10,0),('bebidas-padrao','bebidas','Suco concentrado',20,0),('bebidas-padrao','bebidas','Água',30,0),
('mesa-de-cafe-padrao','mesa-de-cafe','Café',10,0),('mesa-de-cafe-padrao','mesa-de-cafe','Mix de petit fours',20,0),('mesa-de-cafe-padrao','mesa-de-cafe','Bolos',30,0),('mesa-de-cafe-padrao','mesa-de-cafe','Balas finas',40,0),
('bolo-padrao','bolo','Sabor à escolha',10,1),
('doces-padrao','doces','Brigadeiros gourmet',10,0),('doces-padrao','doces','Mix de doces finos',20,0),('doces-padrao','doces','Mini trufas',30,0),('doces-padrao','doces','Camafeus',40,0),
('materiais-padrao','materiais','Rechauds',10,0),('materiais-padrao','materiais','Talheres de inox',20,0),('materiais-padrao','materiais','Pratos de louça brancos',30,0),('materiais-padrao','materiais','Taças de vidro',40,0),
('materiais-crepe','materiais','Crepeira',10,0),('materiais-crepe','materiais','Talheres de inox',20,0),('materiais-crepe','materiais','Pratos de louça brancos',30,0),('materiais-crepe','materiais','Taças de vidro',40,0),
('equipe-padrao','equipe','Garçons',10,0),('equipe-padrao','equipe','Cozinheiras',20,0),('equipe-padrao','equipe','Metriê',30,0),('equipe-padrao','equipe','Copeiras',40,0),('equipe-padrao','equipe','Coordenador',50,0);

INSERT OR IGNORE INTO menu_categories(name,sort_order,active,created_at,updated_at) SELECT DISTINCT section.name,100+section.id,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM seed_shared_items data JOIN menu_sections section ON section.slug=data.section_slug;
INSERT OR IGNORE INTO menu_items(category_id,name,slug,source_label,normalized_name,search_aliases,description,calculation_type,calculation_divisor,calculation_multiplier,calculation_weight,active,created_at,updated_at)
SELECT category.id,data.item_name,data.section_slug||'-'||lower(hex(data.item_name)),data.item_name,data.item_name,'',CASE WHEN data.item_name='Sabor à escolha' THEN 'Configurar sabor, peso, recheio, cobertura, andares, transporte, refrigeração e observações no evento.' ELSE '' END,'menu_only',1,1,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM seed_shared_items data JOIN menu_sections section ON section.slug=data.section_slug JOIN menu_categories category ON category.name=section.name GROUP BY category.id,data.section_slug,data.item_name;
INSERT OR IGNORE INTO menu_shared_block_items(menu_shared_block_id,menu_item_id,sort_order,included,created_at)
SELECT block.id,item.id,data.sort_order,1,CURRENT_TIMESTAMP FROM seed_shared_items data JOIN menu_shared_blocks block ON block.slug=data.block_slug JOIN menu_sections section ON section.slug=data.section_slug JOIN menu_categories category ON category.name=section.name JOIN menu_items item ON item.category_id=category.id AND item.name=data.item_name;

CREATE TEMP TABLE IF NOT EXISTS seed_model_blocks(template_slug TEXT,block_slug TEXT,sort_order INTEGER);
DELETE FROM seed_model_blocks;
INSERT INTO seed_model_blocks
SELECT model.slug,block.slug,CASE block.slug WHEN 'bebidas-padrao' THEN 100 WHEN 'mesa-de-cafe-padrao' THEN 110 WHEN 'bolo-padrao' THEN 120 WHEN 'doces-padrao' THEN 130 WHEN 'materiais-padrao' THEN 140 ELSE 150 END
FROM menu_templates model JOIN menu_shared_blocks block
WHERE model.slug IN ('buffet-especial','buffet-feijoada','buffet-boteco','buffet-comida-mineira','buffet-nordestino','buffet-carnes','buffet-da-casa','buffet-de-massas','buffet-de-churrasco','buffet-carnes-e-massas','buffet-churrasco-fogo-de-chao') AND block.slug IN ('bebidas-padrao','mesa-de-cafe-padrao','bolo-padrao','doces-padrao','materiais-padrao','equipe-padrao');
INSERT INTO seed_model_blocks VALUES
('buffet-crepe-frances','bebidas-padrao',100),('buffet-crepe-frances','bolo-padrao',120),('buffet-crepe-frances','doces-padrao',130),('buffet-crepe-frances','materiais-crepe',140),('buffet-crepe-frances','equipe-padrao',150),
('buffet-brunch','bolo-padrao',120),('buffet-brunch','materiais-padrao',140),('buffet-brunch','equipe-padrao',150),
('buffet-finger-foods','bebidas-padrao',100),('buffet-finger-foods','bolo-padrao',120),('buffet-finger-foods','doces-padrao',130),('buffet-finger-foods','materiais-padrao',140),('buffet-finger-foods','equipe-padrao',150);

INSERT OR IGNORE INTO menu_template_shared_blocks(menu_template_id,menu_shared_block_id,sort_order,created_at) SELECT model.id,block.id,data.sort_order,CURRENT_TIMESTAMP FROM seed_model_blocks data JOIN menu_templates model ON model.slug=data.template_slug JOIN menu_shared_blocks block ON block.slug=data.block_slug;
INSERT OR IGNORE INTO menu_template_sections(menu_template_id,menu_section_id,display_name,sort_order,required,selection_min,selection_max,allow_event_changes,notes,active,created_at,updated_at)
SELECT DISTINCT model.id,section.id,section.name,data.sort_order,1,0,NULL,1,'Bloco compartilhado: '||block.name,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM seed_model_blocks data JOIN menu_templates model ON model.slug=data.template_slug JOIN menu_shared_blocks block ON block.slug=data.block_slug JOIN seed_shared_items shared ON shared.block_slug=block.slug JOIN menu_sections section ON section.slug=shared.section_slug;
INSERT OR IGNORE INTO menu_template_items(menu_template_section_id,menu_item_id,slug,source_label,normalized_name,description,sort_order,included,optional,configurable,notes,active,created_at,updated_at)
SELECT template_section.id,item.id,lower(hex(shared.item_name)),shared.item_name,shared.item_name,item.description,shared.sort_order,1,0,shared.configurable,'Bloco compartilhado: '||block.name,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP
FROM seed_model_blocks data JOIN menu_templates model ON model.slug=data.template_slug JOIN menu_shared_blocks block ON block.slug=data.block_slug JOIN seed_shared_items shared ON shared.block_slug=block.slug JOIN menu_sections section ON section.slug=shared.section_slug JOIN menu_template_sections template_section ON template_section.menu_template_id=model.id AND template_section.menu_section_id=section.id JOIN menu_categories category ON category.name=section.name JOIN menu_items item ON item.category_id=category.id AND item.name=shared.item_name;

DROP TABLE seed_model_blocks;
DROP TABLE seed_shared_items;
DROP TABLE seed_choice_groups;
DROP TABLE seed_menu_content;
