INSERT INTO service_templates(slug,name,description,category,duration_minutes,billing_unit,price_cents,cost_cents,commission_cents,required_team_json,included_materials,excluded_materials,notes,terms,configuration_json,active,current_version,source_name,source_updated_month,created_at,updated_at) VALUES
('fotografia','Fotografia','Serviço de fotografia para o evento.','imagem',NULL,'serviço',NULL,NULL,NULL,'{}','','','','','{"album_printed":false,"pre_event_session":false,"making_of":false}',1,1,'Emeny''s Eventos - Serviços','2025-01',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('filmagem','Filmagem','Cobertura audiovisual da cerimônia e da festa.','imagem',NULL,'serviço',NULL,NULL,NULL,'{}','','','','','{"video_resolution":"Full HD","estimated_final_duration_min":20,"estimated_final_duration_max":40}',1,1,'Emeny''s Eventos - Serviços','2025-01',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('assessoria-completa','Assessoria completa do evento','Assessoria, organização e acompanhamento completo do evento.','assessoria',NULL,'serviço',NULL,NULL,NULL,'{}','','','','','{"initial_contact_days_before_event":30}',1,1,'Emeny''s Eventos - Serviços','2025-01',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('celebrante','Celebrante','Realização de cerimônia religiosa.','cerimonia',NULL,'cerimônia',NULL,NULL,NULL,'{}','','','','','{}',1,1,'Emeny''s Eventos - Serviços','2025-01',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('decoracao','Decoração','Decoração da mesa do bolo, cerimônia, mesas dos convidados e buquê.','decoracao',NULL,'serviço',NULL,NULL,NULL,'{}','','','','','{"guests_per_table":8,"table_quantity_formula":"ceil(guests/8)"}',1,1,'Emeny''s Eventos - Serviços','2025-01',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('decoracao-de-ambiente','Decoração de ambiente','Configuração a definir','decoracao',NULL,'serviço',NULL,NULL,NULL,'{}','','','','','{"reference_photos":[]}',1,1,'Emeny''s Eventos - Serviços','2025-01',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('bar','Bar','Estrutura completa de bar com equipe.','bar',240,'serviço',NULL,NULL,NULL,'{}','','','','','{"included_fruit_options_count":7,"included_duration_hours":4}',1,1,'Emeny''s Eventos - Serviços','2025-01',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('som-e-iluminacao','Som e iluminação','DJ, estrutura de som e iluminação para cerimônia, ambiente e balada.','audiovisual',NULL,'serviço',NULL,NULL,NULL,'{}','','','','','{}',1,1,'Emeny''s Eventos - Serviços','2025-01',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('robo-de-led','Robô de LED','Apresentação de robô de LED durante a balada.','entretenimento',60,'apresentação',NULL,NULL,NULL,'{}','','','','','{"included_duration_hours":1}',1,1,'Emeny''s Eventos - Serviços','2025-01',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('pista-de-led','Pista de LED','Pista iluminada de LED no estilo Paris.','entretenimento',NULL,'serviço',NULL,NULL,NULL,'{}','','','','','{"width_meters":4,"length_meters":4,"style":"Paris"}',1,1,'Emeny''s Eventos - Serviços','2025-01',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('totem-fotografico','Totem fotográfico','Totem com fotos personalizadas, impressão na hora e entrega digital.','imagem',NULL,'serviço',NULL,NULL,NULL,'{}','','','','','{}',1,1,'Emeny''s Eventos - Serviços','2025-01',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT(slug) DO UPDATE SET name=excluded.name,description=excluded.description,category=excluded.category,duration_minutes=excluded.duration_minutes,configuration_json=excluded.configuration_json,source_name=excluded.source_name,source_updated_month=excluded.source_updated_month,updated_at=CURRENT_TIMESTAMP;

INSERT OR IGNORE INTO service_template_versions(service_template_id,version,change_summary,snapshot_json,created_at)
SELECT id,1,'Importação inicial da fonte','{}',CURRENT_TIMESTAMP FROM service_templates;

CREATE TEMP TABLE IF NOT EXISTS seed_service_components(service_slug TEXT,component_name TEXT,category TEXT,included INTEGER,optional INTEGER,configurable INTEGER,sort_order INTEGER,configuration_json TEXT,notes TEXT);
DELETE FROM seed_service_components;
INSERT INTO seed_service_components VALUES
('fotografia','Fotografias ilimitadas','entrega',1,0,0,10,'{}',''),('fotografia','Tratamento das fotografias','entrega',1,0,0,20,'{}',''),('fotografia','Arquivos em alta resolução','entrega',1,0,0,30,'{}',''),('fotografia','Entrega em Drive','entrega',1,0,1,40,'{}',''),
('filmagem','Filmagem em Full HD','cobertura',1,0,0,10,'{"resolution":"Full HD"}',''),('filmagem','Cobertura da cerimônia','cobertura',1,0,0,20,'{}',''),('filmagem','Cobertura da festa','cobertura',1,0,0,30,'{}',''),('filmagem','Entrega em Drive','entrega',1,0,1,40,'{}',''),('filmagem','Vídeo editado entre 20 e 40 minutos','entrega',1,0,1,50,'{"duration_min":20,"duration_max":40}',''),
('assessoria-completa','Assessora','equipe',1,0,1,10,'{}',''),('assessoria-completa','Assistente','equipe',1,0,1,20,'{}',''),('assessoria-completa','Acompanhamento da cerimônia','atividade',1,0,0,30,'{}',''),('assessoria-completa','Acompanhamento da festa','atividade',1,0,0,40,'{}',''),('assessoria-completa','Cronograma completo','documento',1,0,1,50,'{}',''),('assessoria-completa','Organização da igreja','atividade',1,0,0,60,'{}',''),('assessoria-completa','Organização da recepção','atividade',1,0,0,70,'{}',''),('assessoria-completa','Roteiro de horários','documento',1,0,1,80,'{}',''),('assessoria-completa','Orientação','atividade',1,0,0,90,'{}',''),('assessoria-completa','Organização geral do evento','atividade',1,0,0,100,'{}',''),('assessoria-completa','Contato iniciado 30 dias antes','atividade',1,0,0,110,'{"days_before":30}',''),
('celebrante','Cerimônia sem efeito civil','opcao',0,1,1,10,'{}',''),('celebrante','Cerimônia com efeito civil','opcao',0,1,1,20,'{}',''),
('decoracao','Estilo rústico','mesa-do-bolo',0,1,1,10,'{}',''),('decoracao','Arranjos permanentes','mesa-do-bolo',0,1,1,20,'{}',''),('decoracao','Vasos de cristal','mesa-do-bolo',0,1,1,30,'{}',''),('decoracao','Vasos de vidro','mesa-do-bolo',0,1,1,40,'{}',''),('decoracao','Vasos aramados','mesa-do-bolo',0,1,1,50,'{}',''),('decoracao','Vasos de louça','mesa-do-bolo',0,1,1,60,'{}',''),('decoracao','Vasos prateados','mesa-do-bolo',0,1,1,70,'{}',''),('decoracao','Vasos dourados','mesa-do-bolo',0,1,1,80,'{}',''),('decoracao','Bolo fake','mesa-do-bolo',0,1,1,90,'{}',''),('decoracao','Bandejas para doces','mesa-do-bolo',0,1,1,100,'{}',''),('decoracao','Fundo decorativo','mesa-do-bolo',0,1,1,110,'{}',''),('decoracao','Composições para complementação da mesa','mesa-do-bolo',0,1,1,120,'{}',''),
('decoracao','Decoração da entrada dos noivos','cerimonia',0,1,1,130,'{}',''),('decoracao','Vasos rústicos','cerimonia',0,1,1,140,'{}','Alternativa configurável com pilastras de vidro'),('decoracao','Pilastras de vidro','cerimonia',0,1,1,150,'{}','Alternativa configurável com vasos rústicos'),('decoracao','Tapete','cerimonia',0,1,1,160,'{}',''),('decoracao','Passarela','cerimonia',0,1,1,170,'{}',''),('decoracao','Mesa cerimonial','cerimonia',0,1,1,180,'{}',''),('decoracao','Pergolado de madeira','cerimonia',0,1,1,190,'{}','Alternativa configurável com arco de flores'),('decoracao','Arco de flores para o altar','cerimonia',0,1,1,200,'{}','Alternativa configurável com pergolado'),
('decoracao','Mesas redondas','mesas-convidados',1,0,1,210,'{"guests_per_table":8,"formula":"ceil(guests/8)"}',''),('decoracao','Cadeiras de ferro','mesas-convidados',1,0,1,220,'{}',''),('decoracao','Toalhas de tecido Jakar','mesas-convidados',1,0,1,230,'{}',''),('decoracao','Guardanapos de tecido','mesas-convidados',1,0,1,240,'{}',''),('decoracao','Sousplats','mesas-convidados',1,0,1,250,'{}',''),('decoracao','Arranjos de flores permanentes','mesas-convidados',1,0,1,260,'{}',''),('decoracao','Arranjos altos e baixos intercalados','mesas-convidados',1,0,1,270,'{}',''),('decoracao','Buquê da noiva com flores naturais','buque',1,0,1,280,'{}','Modelo à escolha'),
('bar','Estrutura completa de bar','estrutura',1,0,0,10,'{}',''),('bar','Barmen','equipe',1,0,1,20,'{}',''),('bar','Ilha de caipirinhas','estrutura',1,0,0,30,'{}',''),('bar','Caipirinhas com saquê','bebida',1,0,1,40,'{}',''),('bar','Caipirinhas com vodka','bebida',1,0,1,50,'{}',''),('bar','Caipirinhas com cachaça','bebida',1,0,1,60,'{}',''),('bar','Caipirinhas sem álcool','bebida',1,0,1,70,'{}',''),('bar','Sete opções de frutas','insumo',1,0,1,80,'{"count":7}',''),('bar','Gelo','insumo',1,0,1,90,'{}',''),('bar','Canudos','descartavel',1,0,1,100,'{}',''),('bar','Copos de acrílico','descartavel',1,0,1,110,'{}',''),('bar','Guardanapos de papel','descartavel',1,0,1,120,'{}',''),('bar','Quatro horas de serviço','duracao',1,0,1,130,'{"hours":4}',''),
('som-e-iluminacao','DJ','equipe',1,0,1,10,'{}',''),('som-e-iluminacao','Estrutura completa de som','equipamento',1,0,1,20,'{}',''),('som-e-iluminacao','Estrutura de iluminação','equipamento',1,0,1,30,'{}',''),('som-e-iluminacao','Músicas para cerimônia','repertorio',1,0,1,40,'{}',''),('som-e-iluminacao','Música ambiente','repertorio',1,0,1,50,'{}',''),('som-e-iluminacao','Músicas para balada','repertorio',1,0,1,60,'{}',''),
('robo-de-led','Apresentação durante a balada','atividade',1,0,1,10,'{}',''),('robo-de-led','Robô de LED','equipamento',1,0,1,20,'{}',''),('robo-de-led','Canhão de CO2','equipamento',1,0,1,30,'{}',''),('robo-de-led','Uma hora de apresentação','duracao',1,0,1,40,'{"hours":1}',''),
('pista-de-led','Pista de LED','equipamento',1,0,1,10,'{}',''),('pista-de-led','Dimensão de 4 metros por 4 metros','dimensao',1,0,1,20,'{"width_meters":4,"length_meters":4}',''),('pista-de-led','Pista iluminada','caracteristica',1,0,0,30,'{}',''),('pista-de-led','Estilo Paris','caracteristica',1,0,1,40,'{"style":"Paris"}',''),
('totem-fotografico','Fotos ilimitadas','entrega',1,0,0,10,'{}',''),('totem-fotografico','Fotos personalizadas','entrega',1,0,1,20,'{}',''),('totem-fotografico','Impressão e entrega na hora','entrega',1,0,1,30,'{}',''),('totem-fotografico','Foto lembrança','entrega',1,0,1,40,'{}',''),('totem-fotografico','Acessórios para fotografias','material',1,0,1,50,'{}',''),('totem-fotografico','Entrega em Drive','entrega',1,0,1,60,'{}','');

INSERT OR IGNORE INTO service_components(slug,name,description,category,source_label,normalized_name,search_aliases,configurable,active,created_at,updated_at)
SELECT 'component-'||lower(hex(component_name)),component_name,'',category,component_name,component_name,'',MAX(configurable),1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM seed_service_components GROUP BY component_name,category;

INSERT OR IGNORE INTO service_template_components(service_template_id,service_component_id,sort_order,included,optional,configuration_json,notes,active,created_at,updated_at)
SELECT service.id,component.id,data.sort_order,data.included,data.optional,data.configuration_json,data.notes,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM seed_service_components data JOIN service_templates service ON service.slug=data.service_slug JOIN service_components component ON component.slug='component-'||lower(hex(data.component_name));

INSERT OR IGNORE INTO service_choice_groups(service_template_id,slug,name,selection_min,selection_max,selection_required,configurable,created_at,updated_at)
SELECT id,'tipo-de-cerimonia','Tipo de cerimônia',1,1,1,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM service_templates WHERE slug='celebrante';
INSERT OR IGNORE INTO service_choice_group_components(service_choice_group_id,service_template_component_id,sort_order,created_at)
SELECT choice.id,link.id,link.sort_order,CURRENT_TIMESTAMP FROM service_choice_groups choice JOIN service_templates service ON service.id=choice.service_template_id JOIN service_template_components link ON link.service_template_id=service.id JOIN service_components component ON component.id=link.service_component_id WHERE service.slug='celebrante' AND component.name IN ('Cerimônia sem efeito civil','Cerimônia com efeito civil');

DROP TABLE seed_service_components;
